$(document).ready(function(){
	$("#scene03").niceScroll({
		cursorcolor:"#fff",cursorwidth:4,scrollspeed:60,cursorborderradius:0,mousescrollstep:40,cursoropacitymin:0,cursoropacitymax:1,background:"none",cursorborder:"none",autohidemode:false,boxzoom:false,smoothscroll:true,zindex:9999});
		$("#loading .white_box,#loading").addClass("on");$("#gnb .bgm_button").on("click",function(){$(this).toggleClass("off");var g=document.getElementById("sound");if($(this).hasClass("off")){g.muted=true}else{g.muted=false}});$("#gnb .menu_button").on("click",function(){$("#scene_menu").addClass("on");$("#gnb_white").fadeIn()});$("#gnb_white .close").on("click",function(){$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut()});
	$("#gnb_white .menu_button_white").on("click",function(){$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut()});
	$("#left").on("click",function(){if($("#scene05").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene04").addClass("on");$("#right").fadeIn()}else{if($("#scene04").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene03").addClass("on");$("#ascrail2000-hr").addClass("on");$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()}else{if($("#scene03").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene02").addClass("on");$("#ascrail2000-hr").removeClass("on")}else{if($("#scene02").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene01").addClass("on");$("#left").fadeOut();$("#right").fadeOut()}}}}});
	$("#right").on("click",function(){if($("#scene02").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene03").addClass("on");$("#ascrail2000-hr").addClass("on")}else{if($("#scene03").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene04").addClass("on");$("#ascrail2000-hr").removeClass("on")}else{if($("#scene04").hasClass("on")){$(".scrollBox .wrap > div").removeClass("on");$("#scene05").addClass("on");$("#right").fadeOut();$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()}}}});
	$(".small_title,.small_title_white").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene01").addClass("on");$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut();$("#left").fadeOut();$("#right").fadeOut();$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()});
	$("#scene_menu .link_scene li:nth-child(1)").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene02").addClass("on");$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut();$("#left").fadeIn();$("#right").fadeIn();$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()});
	$("#scene_menu .link_scene li:nth-child(2)").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene03").addClass("on");$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut();$("#left").fadeIn();$("#right").fadeIn();$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()});
	$("#scene_menu .link_scene li:nth-child(3)").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene04").addClass("on");$("#left").fadeIn();$("#right").fadeIn();$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut()});
	$("#scene_menu .link_scene li:nth-child(4)").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene05").addClass("on");$("#scene_menu").removeClass("on");$("#gnb_white").fadeOut();$("#left").fadeIn();$("#right").fadeIn();$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()});
	$("#click_button").on("click",function(){$(".scrollBox .wrap > div").removeClass("on");$("#scene02").addClass("on");$("#left").fadeIn();$("#right").fadeIn();$(".scroll_guide").delay(1500).fadeOut(500,function(){$("#fake").addClass("on1")})});
	
	$("#scene02").on("mousewheel",function(g,h){
		if(h>0){if($("#fake").hasClass("on12")){$("#fake").removeClass("on12");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(11)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(11)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(11)").removeClass("up");$("#scene02 .text > li:nth-child(12)").removeClass("on");$("#scene02 .text > li:nth-child(11)").addClass("on");$("#guide2 .guide_white").stop().animate({left:400});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on11")})}
		else{if($("#fake").hasClass("on11")){$("#fake").removeClass("on11");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(10)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(10)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(10)").removeClass("up");$("#scene02 .text > li:nth-child(11)").removeClass("on");$("#scene02 .text > li:nth-child(10)").addClass("on");$("#guide2 .guide_white").stop().animate({left:360});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on10")})}
		else{if($("#fake").hasClass("on10")){$("#fake").removeClass("on10");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(9)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(9)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(9)").removeClass("up");$("#scene02 .text > li:nth-child(10)").removeClass("on");$("#scene02 .text > li:nth-child(9)").addClass("on");$("#guide2 .guide_white").stop().animate({left:320});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on9")})}
		else{if($("#fake").hasClass("on9")){$("#fake").removeClass("on9");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(8)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(8)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(8)").removeClass("up");$("#scene02 .text > li:nth-child(9)").removeClass("on");$("#scene02 .text > li:nth-child(8)").addClass("on");$("#guide2 .guide_white").stop().animate({left:280});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on8")})}
		else{if($("#fake").hasClass("on8")){$("#fake").removeClass("on8");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(7)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(7)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(7)").removeClass("up");$("#scene02 .text > li:nth-child(8)").removeClass("on");$("#scene02 .text > li:nth-child(7)").addClass("on");$("#guide2 .guide_white").stop().animate({left:240});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on7")})}
		else{if($("#fake").hasClass("on7")){$("#fake").removeClass("on7");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(6)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(6)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(6)").removeClass("up");$("#scene02 .text > li:nth-child(7)").removeClass("on");$("#scene02 .text > li:nth-child(6)").addClass("on");$("#guide2 .guide_white").stop().animate({left:200});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on6")})}
		else{if($("#fake").hasClass("on6")){$("#fake").removeClass("on6");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(5)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(5)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(5)").removeClass("up");$("#scene02 .text > li:nth-child(6)").removeClass("on");$("#scene02 .text > li:nth-child(5)").addClass("on");$("#guide2 .guide_white").stop().animate({left:160});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on5")})}
		else{if($("#fake").hasClass("on5")){$("#fake").removeClass("on5");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(4)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(4)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(4)").removeClass("up");$("#scene02 .text > li:nth-child(5)").removeClass("on");$("#scene02 .text > li:nth-child(4)").addClass("on");$("#guide2 .guide_white").stop().animate({left:120});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on4")})}
		else{if($("#fake").hasClass("on4")){$("#fake").removeClass("on4");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(3)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(3)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text_sub").removeClass("on");$("#scene02 .text > li:nth-child(3)").removeClass("up");$("#scene02 .text > li:nth-child(4)").removeClass("on");$("#scene02 .text > li:nth-child(3)").addClass("on");$("#guide2 .guide_white").stop().animate({left:80});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on3")})}
		else{if($("#fake").hasClass("on3")){$("#fake").removeClass("on3");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(2)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(2)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(2)").removeClass("up");$("#scene02 .text > li:nth-child(3)").removeClass("on");$("#scene02 .text > li:nth-child(2)").addClass("on");$("#guide2 .guide_white").stop().animate({left:40});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on2")})}
		else{if($("#fake").hasClass("on2")){$("#fake").removeClass("on2");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(1)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(1)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(1)").removeClass("up");$("#scene02 .text > li:nth-child(2)").removeClass("on");$("#scene02 .text > li:nth-child(1)").addClass("on");$("#guide2 .guide_white").stop().animate({left:0});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on1")})}}}}}}}}}}}}
		
		else{if(h<0){if($("#fake").hasClass("on1")){$("#fake").removeClass("on1");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(2)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(2)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(1)").addClass("up");$("#scene02 .text > li:nth-child(2)").addClass("on");$("#guide2 .guide_white").stop().animate({left:40});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on2")})}
		else{if($("#fake").hasClass("on2")){$("#fake").removeClass("on2");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(3)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(3)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(2)").addClass("up");$("#scene02 .text > li:nth-child(3)").addClass("on");$("#guide2 .guide_white").stop().animate({left:80});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on3")})}
		else{if($("#fake").hasClass("on3")){$("#fake").removeClass("on3");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(4)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(4)").addClass("on");$("#scene02 .text_sub").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(3)").addClass("up");$("#scene02 .text > li:nth-child(4)").addClass("on");$("#guide2 .guide_white").stop().animate({left:120});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on4")})}
		else{if($("#fake").hasClass("on4")){$("#fake").removeClass("on4");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(5)").addClass("on");$("#scene02 .num;_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(5)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(4)").addClass("up");$("#scene02 .text > li:nth-child(5)").addClass("on");$("#guide2 .guide_white").stop().animate({left:160});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on5")})}
		else{if($("#fake").hasClass("on5")){$("#fake").removeClass("on5");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(6)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(6)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(5)").addClass("up");$("#scene02 .text > li:nth-child(6)").addClass("on");$("#guide2 .guide_white").stop().animate({left:200});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on6")})}
		else{if($("#fake").hasClass("on6")){$("#fake").removeClass("on6");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(7)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(7)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(6)").addClass("up");$("#scene02 .text > li:nth-child(7)").addClass("on");$("#guide2 .guide_white").stop().animate({left:240});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on7")})}
		else{if($("#fake").hasClass("on7")){$("#fake").removeClass("on7");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(8)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(8)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(7)").addClass("up");$("#scene02 .text > li:nth-child(8)").addClass("on");$("#guide2 .guide_white").stop().animate({left:280});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on8")})}
		else{if($("#fake").hasClass("on8")){$("#fake").removeClass("on8");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(9)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(9)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(8)").addClass("up");$("#scene02 .text > li:nth-child(9)").addClass("on");$("#guide2 .guide_white").stop().animate({left:320});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on9")})}
		else{if($("#fake").hasClass("on9")){$("#fake").removeClass("on9");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(10)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(10)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(9)").addClass("up");$("#scene02 .text > li:nth-child(10)").addClass("on");$("#guide2 .guide_white").stop().animate({left:360});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on10")})}
		else{if($("#fake").hasClass("on10")){$("#fake").removeClass("on10");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(11)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(11)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(10)").addClass("up");$("#scene02 .text > li:nth-child(11)").addClass("on");$("#guide2 .guide_white").stop().animate({left:400});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on11")})}
		else{if($("#fake").hasClass("on11")){$("#fake").removeClass("on11");$("#scene02 .bg > li").removeClass("on");$("#scene02 .bg > li:nth-child(12)").addClass("on");$("#scene02 .num_image > li").removeClass("on");$("#scene02 .num_image > li:nth-child(12)").addClass("on");$("#scene02 .text > li").removeClass("on");$("#scene02 .text > li:nth-child(11)").addClass("up");$("#scene02 .text > li:nth-child(12)").addClass("on");$("#guide2 .guide_white").stop().animate({left:440});$("#fake").delay(1200).fadeOut(1,function(){$("#fake").addClass("on12")})}}}}}}}}}}}}}});
		
		$("#name .more_cast_button").on("click",function(){$("#cast_popup").fadeIn()});
		$("#cast_popup .popup_exit_button").on("click",function(){$("#cast_popup").fadeOut()});
		
		var e=document.getElementById("sc03_banner_video1");
		var d=document.getElementById("sc03_banner_video2");
		$("#profile_img .scene_02").on("mouseenter",function(){e.play()});
		$("#profile_img .scene_02").on("mouseleave",function(){e.pause()});
		$("#profile_img .scene_03").on("mouseenter",function(){d.play()});
		$("#profile_img .scene_03").on("mouseleave",function(){d.pause()});
		$("#cast_popup .popup_contents").slidesjs({width:1029,height:349,play:{active:false,interval:3000,effect:"slide",auto:false,pauseOnHover:false,restartDelay:2500},navigation:{active:true,effect:"slide"},pagination:{active:true,effect:"slide"},effect:{fade:{speed:800},slide:{speed:1600}},callback:{loaded:function(g){f()},start:function(g){f()},complete:function(g){}}});function c(){$("#guide3 .popup_guide_white").stop().animate({left:814})}function b(){$("#guide3 .popup_guide_white").stop().animate({left:911})}function a(){$("#guide3 .popup_guide_white").stop().animate({left:1008})}function f(){
			if($("#cast_popup .popup_contents .slidesjs-pagination li").eq(0).find("a").hasClass("active")){c()}
			if($("#cast_popup .popup_contents .slidesjs-pagination li").eq(1).find("a").hasClass("active")){b()}
			if($("#cast_popup .popup_contents .slidesjs-pagination li").eq(2).find("a").hasClass("active")){a()}}$("#cast_popup .popup_prev_button").on("click",function(){$("#cast_popup .popup_contents .slidesjs-previous").trigger("click")});$("#cast_popup .popup_next_button").on("click",function(){$("#cast_popup .popup_contents .slidesjs-next").trigger("click")});$("#video_navigation .button_play").on("click",function(){$("#video_navigation .button_play").fadeOut();$("#video_navigation .button_pause").fadeIn();var g=document.getElementById("sc04_video");g.play()});$("#video_navigation .button_pause").on("click",function(){$("#video_navigation .button_pause").fadeOut();$("#video_navigation .button_play").fadeIn();var g=document.getElementById("sc04_video");g.pause()})});$(function(){$(".naviJs > li > a, .topBtn").click(function(){var b=$($(this).attr("href")).position().top;var a=$(".gnb").innerHeight();$(".scrollBox").stop().animate({scrollTop:b-a},1200,"easeInOutExpo");return false});$(".scrollBox").scroll(function(){var a=$(".scrollBox").scrollTop();$(".posNum").text(a);$(".wrap > div").each(function(c){var d=100;var b=$(".wrap > div:first").position().top;var e=$(this).position().top;if(a<=b-d){$(".naviJs").each(function(){$("li",this).removeClass("on").eq(0).addClass("on")})}
			else{if(a>=e-d){$(".naviJs").each(function(){$("li",this).removeClass("on").eq(c).addClass("on")})}}})})});